support plugins
* plugin support
* versioned or latest plugin
* support parameters for cloning
* plugin properties in plugin yml file
* plugin properties default in plugin script file
* plugin properties in shrendd.yml file

diff --git a/main/shrendd b/main/shrendd
--- a/main/shrendd
+++ b/main/shrendd
@@ -165,20 +165,33 @@ function curlD {
 
 function curlDS {
   #curl --output $SHRENDD_DIR/$1$2 -L "$3"
-  curlD "$SHRENDD_DIR/$1$2" "$3"
+  if [ $# -gt 3 ]; then
+    curlD "$SHRENDD_DIR/$1$2" "$3" "$4"
+  else
+    curlD "$SHRENDD_DIR/$1$2" "$3"
+  fi
 }
 
 function wgetD {
+#  echo "wgetting..."
   if [ $# -gt 2 ]; then
+#    echo "  with parameters: $3"
     wget --output-document="$1" "$2" $3
   else
-    wget --output-document="$1" "$2" $3
+#    echo "  without parameters"
+    wget --output-document="$1" "$2"
   fi
+#  echo "wgotten..."
 }
 
 function wgetDS {
   #wget --output-document=$SHRENDD_DIR/$1$2 "$3"
-  wgetD "$SHRENDD_DIR/$1$2" "$3"
+    if [ $# -gt 3 ]; then
+#      echo "  with parameters: $4"
+      wgetD "$SHRENDD_DIR/$1$2" "$3" "$4"
+    else
+      wgetD "$SHRENDD_DIR/$1$2" "$3"
+    fi
 }
 
 function trueName {
@@ -236,32 +249,47 @@ function shrenddOrDefault {
     _value="$(echo ${!_parm})"
   else
     _plugin=$(echo "$1" | cut -d'.' -f1)
+#    if [[ "$_plugin" == *"crib"* ]]; then
+#      echo "crib shrendd property retrieval"
+#    fi
     if [[ "$_plugin" == "shrendd" ]]; then
       _value=$(echo "$_SHRENDD" | yq e ".$1" -)
       if [ -z "$_value" ] || [ "$_value" == "null" ]; then
         _value=$(echo "$_SHRENDD_DEFAULTS" | yq e ".$1" -)
       fi
     else
-      _plugin_location=$(shrenddOrDefault "shrendd.plugins.$(_plugin).config.dir" || echo "./$_the_module/$(_plugin).yml")
-      _plugin_yaml=$(shrenddOrDefault "shrendd.module.$_the_module.properties" || echo "./$_the_module/shrendd.yml")
+      _plugin_location=$(shrenddOrDefault "shrendd.plugins.$_plugin.config.dir" || echo "./$_plugin.yml")
+#      _plugin_yaml=$(shrenddOrDefault "shrendd.module.$_the_module.properties" || echo "./$_the_module/shrendd.yml")
       if [ "${_plugin_location}" == "null" ]; then
-        _plugin_location="./$_the_module/$(_plugin).yml"
+        _plugin_location="./$_the_module/$_plugin.yml"
       fi
       if [ -f $_plugin_location ]; then
         :
       else
-        _plugin_location="./$(_plugin).yml"
+        _plugin_location="./$_plugin.yml"
       fi
       if [ -f $_plugin_location ]; then
+#        if [[ "$_plugin" == "crib" ]]; then
+#          echo "crib shrendd property retrieval from file"
+#        fi
         _plugin_yaml=$(echo "$_SHRENDD" | yq eval-all '. as $item ireduce ({}; . * $item )' - $_plugin_location)
       else
+#        if [[ "$_plugin" == "crib" ]]; then
+#          echo "crib shrendd property retrieval from default shrend"
+#        fi
         _plugin_yaml="$_SHRENDDO"
       fi
       _value=$(echo "$_plugin_yaml" | yq e ".$1" -)
 #      export _SHRENDD=$(echo "$_SHRENDDO" | yq eval-all '. as $item ireduce ({}; . * $item )' - $_module_shrendd_yaml)
       if [ -z "$_value" ] || [ "$_value" == "null" ]; then
         _plugin_defaults=""
+#        if [[ "$_plugin" == "crib" ]]; then
+#          echo "crib property not found..."
+#        fi
         if [[ $(type -t $_plugin) == function ]]; then
+#          if [[ "$_plugin" == "crib" ]]; then
+#            echo "crib loading plugin function..."
+#          fi
           _plugin_defaults=$(eval "$_plugin")
         fi
         if [[ -n "$_plugin_defaults" ]]; then
@@ -315,13 +343,23 @@ function isUpToDate {
     fi
     if [ -f $_the_dir/version.yml ]; then
       _SHRENDD_CURRENT_VERSION=$(yq e ".shrendd.version" $_the_dir/version.yml)
+      if [[ "$_SHRENDD_CURRENT_VERSION" == "null" ]]; then
+        _SHRENDD_CURRENT_VERSION=$(yq e ".version" $_the_dir/version.yml)
+      fi
       if [ "$4" == "latest" ]; then
         if [ -d $_the_dir/.latest ]; then
           rm -rf $_the_dir/.latest
         fi
         mkdir $_the_dir/.latest
-        eval "$1 \"$_the_dir/.latest/version\" \".yml\" \"$3/version.yml\""
+        if [ $# -gt 5 ]; then
+          eval "$1 \"$_the_dir/.latest/version.yml\" \"$3/version.yml\" \"$6\""
+        else
+          eval "$1 \"$_the_dir/.latest/version.yml\" \"$3/version.yml\""
+        fi
         _SHRENDD_LATEST_VERSION=$(yq e ".shrendd.version" $_the_dir/.latest/version.yml)
+        if [[ "$_SHRENDD_LATEST_VERSION" == "null" ]]; then
+          _SHRENDD_LATEST_VERSION=$(yq e ".version" $_the_dir/.latest/version.yml)
+        fi
         if [ "$_SHRENDD_LATEST_VERSION" == "$_SHRENDD_CURRENT_VERSION" ]; then
           _SHRENDD_IS_UPTODATE="true"
         else
@@ -376,8 +414,10 @@ function initTargets {
     if [[ $# -gt 0 && "${_target}" != "render" ]]; then
       _target_source=$(shrenddOrDefault "shrendd.${_target}.source" 1)
       #cloneShrendd "$_GETTER" "$_target"
-      echo "shrendd.${_target}.source: ${_target_source}"
-      eval "${_target_source}"
+      if [[ "$_target_source" != "null" ]]; then
+          echo "shrendd.${_target}.source: ${_target_source}"
+        eval "${_target_source}"
+      fi
     fi
   done
   echo "targets initialized"
@@ -385,16 +425,22 @@ function initTargets {
 }
 
 function cloneShrendd {
-  clonePlugin "$1" "$2" "$_SHRENDD_VERSION" "$_SHRENDD_GIT_URL" "shrendd"
+  if [ "$_SHRENDD_VERSION" == "latest" ]; then
+    _ARTIFACT_URL="$_SHRENDD_GIT_URL/releases/latest/download"
+  else
+    _ARTIFACT_URL="$_SHRENDD_GIT_URL/releases/download/v$_SHRENDD_VERSION"
+  fi
+  clonePlugin "$1" "$2" "$_SHRENDD_VERSION" "$_ARTIFACT_URL" "shrendd"
 }
 
 function clonePlugin {
-  if [ "$3" == "latest" ]; then
-    _ARTIFACT_URL="$4/releases/latest/download"
+  _ARTIFACT_URL="$4"
+  _clone_parameters=$(shrenddOrDefault "shrendd.plugins.$2.parameters")
+  if [[ "$_clone_parameters" == "null" ]]; then
+    _IS_UPTODATE_NOW=$(isUpToDate "$1" "$2" "$_ARTIFACT_URL" "$3" "$5")
   else
-    _ARTIFACT_URL="$4/releases/download/v$3"
+    _IS_UPTODATE_NOW=$(isUpToDate "$1" "$2" "$_ARTIFACT_URL" "$3" "$5" "$_clone_parameters")
   fi
-  _IS_UPTODATE_NOW=$(isUpToDate "$1" "$2" "$_ARTIFACT_URL" "$3" "$5")
   echo "$2 uptodate: $_IS_UPTODATE_NOW"
   if [ "$_IS_UPTODATE_NOW" == "true" ]; then
     :
@@ -404,13 +450,19 @@ function clonePlugin {
     else
       mkdir "$SHRENDD_DIR"
     fi
-    echo "downloading shrendd:$3"
+    echo "downloading $5:$3"
     if [ -d $SHRENDD_DIR/$2 ]; then
       rm -rf $SHRENDD_DIR/$2
     fi
     rm -f $SHRENDD_DIR/$2.zip
     echo "downloading with $1...$2"
-    eval "${1}S \"$2\" \".zip\" \"$_ARTIFACT_URL/$2.zip\""
+    #curlD or wgetD...
+    if [[ "$_clone_parameters" == "null" ]]; then
+      eval "${1}S \"$2\" \".zip\" \"$_ARTIFACT_URL/$2.zip\""
+    else
+      eval "${1}S \"$2\" \".zip\" \"$_ARTIFACT_URL/$2.zip\" \"$_clone_parameters\""
+    fi
+    echo "download finished..."
     if [[ "$1" == "devD"* ]]; then
       echo "cloned locally, nothing to unzip."
     else
@@ -431,12 +483,31 @@ function initPlugins {
     echo -e "plugs:\n$_plugins"
     _plugin_list=$(keysFor "$_plugins")
     _plugs=" "
+    echo "loading plugins"
     for _plug in $_plugin_list; do
       _plug=$(echo "$_plug" | cut -d'.' -f1)
       if [[ "$_plugs" == *" $_plug "* ]]; then
         :
       else
+        _clone_parameters=$(shrenddOrDefault "shrendd.plugins.$_plug.parameters")
+        echo "  $_plug parameters: $_clone_parameters"
         _plugs="$_plugs$_plug "
+#        \"$_GETTER\" \"test\"
+        _plug_version=$(echo "$_plugins" | yq e ".$_plug.version" -)
+        _plug_src=$(echo "$_plugins" | yq e ".$_plug.source" -)
+        _plug_getter="$_GETTER"
+        _plug_getter_=$(echo "$_plugins" | yq e ".$_plug.getter" -)
+        if [[ "$_plug_getter_" == "null" ]]; then
+          :
+        else
+          _plug_getter="$_plug_getter_"
+        fi
+        clonePlugin "$_plug_getter" "$_plug" "$_plug_version" "$_plug_src" "plugin"
+        echo "plugin cloned......"
+        if [[ -f "$SHRENDD_DIR/$_plug/$_plug" ]]; then
+          echo "sourcing plugin: $_plug"
+          source "$SHRENDD_DIR/$_plug/$_plug"
+        fi
       fi
 #      _targets="$_targets $(echo "$_targ" | grep ".targets.[0-9]\+.name" || echo "")"
     done
@@ -508,6 +579,13 @@ fi
 
 cloneShrendd "$_GETTER" "render"
 source $SHRENDD_DIR/parse_parameters.sh
+#bootstrap any add ons or other stuff before shrendding.
+if [ -f ./plugin.shrendd ]; then
+  echo "found a plugin.shrendd file, sourcing it now..."
+  source ./plugin.shrendd
+else
+  echo "no plugin.shrendd found"
+fi
 initPlugins
 #exit 0
 
