support stub and move exit function to main shrendd file
add a "stub" feature for stubbing predefined templates.
move the resetLocal exit trap to shrendd and properly loop over types for deleting the render directory.

diff --git a/main/shrendd b/main/shrendd
--- a/main/shrendd
+++ b/main/shrendd
@@ -1,6 +1,28 @@
 #!/bin/bash
 set -euo pipefail
 
+trap resetLocal EXIT
+
+function resetLocal {
+  if [ -f $_DEPLOY_ERROR_DIR/render_warning.log ]; then
+    echo "warnings during shrendd:"
+    cat $_DEPLOY_ERROR_DIR/render_warning.log | sed -e "s/^/  /g"
+  fi
+  if [ $? -ne 0 ] || [ -f $_DEPLOY_ERROR_DIR/render_error.log ]; then
+    echo "It seems there was an error during the process. Please review the logs for more information."
+    if [ -f $_DEPLOY_ERROR_DIR/render_error.log ]; then
+      echo "errors during shrendd:"
+      cat $_DEPLOY_ERROR_DIR/render_error.log | sed -e "s/^/  /g"
+    fi
+  fi
+  if [ "$_is_debug" == true ]; then
+    echo "running as debug, not deleting render directories"
+  else
+    echo "was live, should be deleting render directories"
+    stageLeft
+  fi
+}
+
 function checkCommand {
   if command -v "$1" &> /dev/null; then
     :
@@ -39,9 +61,9 @@ shrendd:
   - name: k8s
     description: just testing extra fields in the array element
   config:
-    path: .
+    path: ./config
     validate: true
-    definition: config/config-template.yml
+    definition: $(shrenddOrDefault shrendd.config.path)/config-template.yml
   k8s:
     source: "cloneShrendd \"$_GETTER\" \"k8s\""
     yaml:
@@ -62,6 +84,7 @@ function devD {
   if [ "$1" == "render" ]; then
     echo "copy additional render scripts..."
     cp -rf $_source/deploy.sh ./.shrendd/
+    cp -rf $_source/stub.sh ./.shrendd/
     cp -rf $_source/parse_parameters.sh ./.shrendd/
     cp -rf $_source/upshrendd ./.shrendd/
   fi
@@ -279,4 +302,13 @@ done
 export targets="$_targets"
 export SHRENDD_WORKING_DIR=$(pwd)
 source ./.shrendd/parse_parameters.sh
-source ./.shrendd/deploy.sh
+export _config=$(shrenddOrDefault shrendd.config.path)/${_config}
+echo "======================================================="
+echo "                 best shrendds forever                 "
+echo "using: $_config"
+if [[ $_stub == "false" ]]; then
+  source ./.shrendd/deploy.sh
+else
+  echo "stubbing: $_stub/toes"
+  source ./.shrendd/stub.sh
+fi
