39 plugin vscode initial simple preview plugin (#41)
* initial vscode plugin

* creates vscode plugin project
* basic window with edit and preview tab
* initial attempt at detecting shrendd and trying to run it (although this doesn't work yet)

* working version loading hardcoded module (and target) build dir

* clean up comments and ignore vsix files

* detect module

* collect default and module specific propertie

establishes a map of shrendd module properties and looks up new modules/targets not yet loaded.
uses default properties to calculate the module.

* calculated module and determined final target build directory

* library module support

* specify library module with '>'
* --target targetname support that overrides the list of targets in shrendd.config
* test updates for --get-property changes

* bump to 0.17.0

* preserve new file contents on window refocus

* implement monaco editor in vscode plugin

* quote paths in commands

there was an issue where a lot of the commands take a file or directory path and were not quoting the value, causing issues if there are spaces present.

* stylized simple text editor

monaco is too messy to build into a functional vscode plugin, implementing a stylized custom editor instead of monaco.

* clean up k8s chmod

* improve path handling when space is present

fix a few places where paths were not properly quoted and the space caused some bad things to happen.
update upshrendd with quoted paths.

* include seconds with minutes in test execution time

* fix templating path handling

* wrap file paths in double quotes for template handling
* improve handling of file paths in loops for k8s afterrender

* update tests

* run tests in parallel
* add duplicate tests but with a space in the path somewhere
* simple performance tests

* check if there is a need to build or not

* selected tab, shrendd status message, and force refresh

selected tab supported
status message with informational messages
force refresh stubbed, but not yet functional.

* handle dispose and multiple preview attempts

* Delete basic.txt

* better state management and force refresh

* improve state handling between switching tabs and views
* preserve force refresh globally
* show last status message on view load
* support force refresh to force a shrendd build of the target module.

* initial plugin property loading

* refactor exec for running shrendd and get property values

* save shrenddeditor settings to file

* save properties to file
* respect file modified times to determine if properties need to be re-evaluated

* initialize target config paths and improved stale handling

* empty list of config yaml files loaded

* filter out config definition from render list

* refactor module initialization

* pre-loading module settings and rendering selected config yaml

* show error log if problem shrendding and default to build if selected config is no longer an option

* update dependency versions and helloWorld readme

* refactor to standardized "get" settings

* standardize on `get.src`, `get.method`, `get.parameters`
* introduce `GET_ARTIFACT`, `GET_ARTIFACT_ID`, `GET_ARTIFACT_EXTENSION` available for use in `get.src` strings.

* escape the escapes in yaml to avoid issues with keys

* extra test case just incase...

* update build: build and publish shrendditor

* update build to build vscode plugin and publish it

diff --git a/documents/examples/helloWorld/shrendd b/documents/examples/helloWorld/shrendd
--- a/documents/examples/helloWorld/shrendd
+++ b/documents/examples/helloWorld/shrendd
@@ -4,6 +4,7 @@ set -euo pipefail
 trap resetLocal EXIT
 
 export FORCE_SHRENDD_UPDATES="false"
+export GIVEN_TARGETS=""
 export LOG_VERBOSE="false"
 export _RED='\033[0;31m'
 export _BLUE='\033[0;34m'
@@ -45,7 +46,7 @@ shrendd:
     this:
       get:
         method: "getThis"
-        src: "$(shrenddOrDefault shrendd.deploy.dir)"
+        src: "$(shrenddOrDefault shrendd.working.dir)"
 EndOfYml
 }
 
@@ -101,38 +102,42 @@ EndOfYml
 }
 
 function resetLocal {
-  if [[ -v _DEPLOY_ERROR_DIR ]]; then  
-    if [ -f $_DEPLOY_ERROR_DIR/render_info.log ]; then
-      shrenddEchoIfNotSilent "information during shrendd:"
-      cat $_DEPLOY_ERROR_DIR/render_info.log | sed -e "s/^/  /g"
-    fi
-    if [ -f $_DEPLOY_ERROR_DIR/render_warning.log ]; then
-      shrenddEchoIfNotSilent "${_TEXT_WARN}warnings during shrendd:"
-      cat $_DEPLOY_ERROR_DIR/render_warning.log | sed -e "s/^/  /g"
-    fi
-    if [ $? -ne 0 ] || [ -f $_DEPLOY_ERROR_DIR/render_error.log ]; then
-      shrenddEchoIfNotSilent "${_TEXT_ERROR}It seems there was an error during the process. Please review the logs for more information."
-      if [ -f $_DEPLOY_ERROR_DIR/render_error.log ]; then
-        shrenddEchoIfNotSilent "errors during shrendd:"
-        cat $_DEPLOY_ERROR_DIR/render_error.log | sed -e "s/^/  /g"
+  if [[ "$_IS_SILENT" == "0" ]]; then
+    if [[ -v _DEPLOY_ERROR_DIR ]]; then
+      if [ -f "$_DEPLOY_ERROR_DIR/render_info.log" ]; then
+        shrenddEchoIfNotSilent "information during shrendd:"
+        cat "$_DEPLOY_ERROR_DIR/render_info.log" | sed -e "s/^/  /g"
+      fi
+      if [ -f "$_DEPLOY_ERROR_DIR/render_warning.log" ]; then
+        shrenddEchoIfNotSilent "${_TEXT_WARN}warnings during shrendd:"
+        cat "$_DEPLOY_ERROR_DIR/render_warning.log" | sed -e "s/^/  /g"
+      fi
+      if [ $? -ne 0 ] || [ -f "$_DEPLOY_ERROR_DIR/render_error.log" ]; then
+        shrenddEchoIfNotSilent "${_TEXT_ERROR}It seems there was an error during the process. Please review the logs for more information."
+        if [ -f "$_DEPLOY_ERROR_DIR/render_error.log" ]; then
+          shrenddEchoIfNotSilent "errors during shrendd:"
+          cat "$_DEPLOY_ERROR_DIR/render_error.log" | sed -e "s/^/  /g"
+        fi
+      fi
+      shrenddEchoIfNotSilent "${_CLEAR_TEXT_COLOR}"
+      if [[ -v _is_debug ]]; then
+        if [ "$_is_debug" == true ]; then
+          shrenddEchoIfNotSilent "running as debug, not deleting render directories"
+        else
+          shrenddEchoIfNotSilent "was live, should be deleting render directories"
+          stageLeft
+        fi
       fi
     fi
-    shrenddEchoIfNotSilent -en "${_CLEAR_TEXT_COLOR}"
-    if [[ -v _is_debug ]]; then
-      if [ "$_is_debug" == true ]; then
-        shrenddEchoIfNotSilent "running as debug, not deleting render directories"
-      else
-        shrenddEchoIfNotSilent "was live, should be deleting render directories"
-        stageLeft
-      fi
-    fi
+    shrenddEchoIfNotSilent "${_TEXT_INFO}end of shrendd${_CLEAR_TEXT_COLOR}"
   fi
-  shrenddEchoIfNotSilent "${_TEXT_INFO}end of shrendd${_CLEAR_TEXT_COLOR}"
 }
 
 function shrenddEchoIfNotSilent {
   if [[ "$_IS_SILENT" == "0" ]]; then
     shrenddEcho "$1"
+  else
+    shrenddLog "$1"
   fi
 }
 
@@ -151,16 +156,16 @@ function dateTimeStamp {
 
 function shrenddLog {
   if [[ -v _DEPLOY_ERROR_DIR ]]; then
-    if [ -d $_DEPLOY_ERROR_DIR ]; then
+    if [ -d "$_DEPLOY_ERROR_DIR" ]; then
       :
     else
-      mkdir -p $_DEPLOY_ERROR_DIR
+      mkdir -p "$_DEPLOY_ERROR_DIR"
     fi
     if [[ "${LOG_VERBOSE}" == "true" ]]; then
       if [[ $# -gt 1 ]]; then
-        echo -e "$(dateTimeStamp): $1" >> $_DEPLOY_ERROR_DIR/shrendd.log
+        echo -e "$(dateTimeStamp): $1" >> "$_DEPLOY_ERROR_DIR/shrendd.log"
       else
-        echoSensitive "$(dateTimeStamp): $1" "true" >> $_DEPLOY_ERROR_DIR/shrendd.log
+        echoSensitive "$(dateTimeStamp): $1" "true" >> "$_DEPLOY_ERROR_DIR/shrendd.log"
       fi
     fi
   fi
@@ -196,10 +201,10 @@ function echoSensitive {
 function checkShrenddVersion {
   _UPSHRENDD_VERSION="0.0.0-dev"
   _SHRENDD_CURRENT_VERSION="$_UPSHRENDD_VERSION"
-  if [ -f $SHRENDD_DIR/version.yml ]; then
-    _SHRENDD_CURRENT_VERSION=$(yq e ".shrendd.version" $SHRENDD_DIR/version.yml)
+  if [ -f "$SHRENDD_DIR/version.yml" ]; then
+    _SHRENDD_CURRENT_VERSION=$(yq e ".shrendd.version" "$SHRENDD_DIR/version.yml")
   fi
-  if [[ $_UPSHRENDD_VERSION == $_SHRENDD_CURRENT_VERSION ]]; then
+  if [[ "$_UPSHRENDD_VERSION" == "$_SHRENDD_CURRENT_VERSION" ]]; then
     :
   else
     echo -e "${_TEXT_INFO}shrendd file does not match shrendd version, consider running $SHRENDD_DIR/upshrendd${_CLEAR_TEXT_COLOR}"
@@ -218,7 +223,7 @@ function checkCommand {
 }
 
 function checkFile {
-  if [ -f $1 ]; then
+  if [ -f "$1" ]; then
     echo "true"
   else
     echo "false"
@@ -236,7 +241,7 @@ function shrenddStub {
     _stub_shrendd=$(shrenddOrDefault "shrendd.config.stub")
     if [[ "$_stub_shrendd" == "true" ]]; then
       echo "stubbing $_SHREND_YML"
-      echo -e "$(defaultShrendd)" > $_SHREND_YML
+      echo -e "$(defaultShrendd)" > "$_SHREND_YML"
     fi
   fi
 }
@@ -247,19 +252,19 @@ function getThis {
 
 function devDS {
   shrenddEchoIfNotSilent "you must be a developer of shrendd and running a test, copying latest '$1' from shrendd_src"
-  if [ -d $SHRENDD_DIR/$1 ]; then
+  if [ -d "$SHRENDD_DIR/$1" ]; then
     shrenddLog "devDS: rm $SHRENDD_DIR/$1"
-    rm -rf $SHRENDD_DIR/$1
+    rm -rf "$SHRENDD_DIR/$1"
   fi
   _source=$(shrenddOrDefault "shrendd.test.local")
-  cp -rf $_source/$1 $SHRENDD_DIR/$1
+  cp -rf "$_source/$1" "$SHRENDD_DIR/$1"
   if [ "$1" == "render" ]; then
     shrenddEchoIfNotSilent "copy additional render scripts..."
-    cp -rf $_source/deploy.sh $SHRENDD_DIR/
-    cp -rf $_source/stub.sh $SHRENDD_DIR/
-    cp -rf $_source/parse_parameters.sh $SHRENDD_DIR/
-    cp -rf $_source/upshrendd $SHRENDD_DIR/
-    cp -rf $_source/version.yml $SHRENDD_DIR/
+    cp -rf "$_source/deploy.sh" "$SHRENDD_DIR/"
+    cp -rf "$_source/stub.sh" "$SHRENDD_DIR/"
+    cp -rf "$_source/parse_parameters.sh" "$SHRENDD_DIR/"
+    cp -rf "$_source/upshrendd" "$SHRENDD_DIR/"
+    cp -rf "$_source/version.yml" "$SHRENDD_DIR/"
   fi
 }
 
@@ -335,33 +340,10 @@ function testIf {
   fi
 }
 
-function shrenddOrDefaultDebug {
-  _value=""
-  echo "debugging..."
-  trueName $1
-  if [ "$(testIf $1)" == "true" ]; then
-    echo "found truth!!!"
-    _parm=$(trueName $1)
-    _value="$(echo ${!_parm})"
-  else
-    echo "nothing found..."
-    _value=$(echo "$_SHRENDD" | yq e ".$1" -)
-    if [ -z "$_value" ] || [ "$_value" == "null" ]; then
-      _value=$(echo "$_SHRENDD_DEFAULTS" | yq e ".$1" -)
-    fi
-  fi
-  if [ -z "${2+x}" ] || [ "$2" -lt 1 ]; then
-    echo $(eval echo "$_value")
-  else
-    echo -e "$_value"
-  fi
-  echo "...debugging"
-}
-
 function shrenddOrDefault {
   _value=""
-  if [ "$(testIf $1)" == "true" ]; then
-    _parm=$(trueName $1)
+  if [ "$(testIf "$1")" == "true" ]; then
+    _parm=$(trueName "$1")
     _value="$(echo ${!_parm})"
   else
     _plugin=$(echo "$1" | cut -d'.' -f1)
@@ -379,13 +361,13 @@ function shrenddOrDefault {
       if [ "${_plugin_location}" == "null" ]; then
         _plugin_location="./$_the_module/$_plugin.yml"
       fi
-      if [ -f $_plugin_location ]; then
+      if [ -f "$_plugin_location" ]; then
         :
       else
         _plugin_location="./$_plugin.yml"
       fi
-      if [ -f $_plugin_location ]; then
-        _plugin_yaml=$(echo "$_SHRENDD" | yq eval-all '. as $item ireduce ({}; . * $item )' - $_plugin_location)
+      if [ -f "$_plugin_location" ]; then
+        _plugin_yaml=$(echo "$_SHRENDD" | yq eval-all '. as $item ireduce ({}; . * $item )' - "$_plugin_location")
       else
         _plugin_yaml="$_SHRENDDO"
       fi
@@ -441,29 +423,29 @@ function isUpToDate {
   if [ "$1" == "devD" ]; then
     _SHRENDD_IS_UPTODATE="false"
   else
-    _the_dir=$SHRENDD_DIR
+    _the_dir="$SHRENDD_DIR"
     if [ "$5" == "plugin" ]; then
       _the_dir="$_the_dir/$2"
     fi
-    if [ -f $_the_dir/version.yml ]; then
-      _SHRENDD_CURRENT_VERSION=$(yq e ".shrendd.version" $_the_dir/version.yml)
+    if [ -f "$_the_dir/version.yml" ]; then
+      _SHRENDD_CURRENT_VERSION=$(yq e ".shrendd.version" "$_the_dir/version.yml")
       if [[ "$_SHRENDD_CURRENT_VERSION" == "null" ]]; then
-        _SHRENDD_CURRENT_VERSION=$(yq e ".version" $_the_dir/version.yml)
+        _SHRENDD_CURRENT_VERSION=$(yq e ".version" "$_the_dir/version.yml")
       fi
       if [ "$4" == "latest" ]; then
-        if [ -d $_the_dir/.latest ]; then
+        if [ -d "$_the_dir/.latest" ]; then
           shrenddLog "isUpToDate: rm ${_the_dir}/.latest"
-          rm -rf $_the_dir/.latest
+          rm -rf "$_the_dir/.latest"
         fi
-        mkdir $_the_dir/.latest
+        mkdir "$_the_dir/.latest"
         if [ $# -gt 5 ]; then
           eval "$1 \"$_the_dir/.latest/version.yml\" \"$3/version.yml\" \"$6\""
         else
           eval "$1 \"$_the_dir/.latest/version.yml\" \"$3/version.yml\""
         fi
-        _SHRENDD_LATEST_VERSION=$(yq e ".shrendd.version" $_the_dir/.latest/version.yml)
+        _SHRENDD_LATEST_VERSION=$(yq e ".shrendd.version" "$_the_dir/.latest/version.yml")
         if [[ "$_SHRENDD_LATEST_VERSION" == "null" ]]; then
-          _SHRENDD_LATEST_VERSION=$(yq e ".version" $_the_dir/.latest/version.yml)
+          _SHRENDD_LATEST_VERSION=$(yq e ".version" "$_the_dir/.latest/version.yml")
         fi
         if [ "$_SHRENDD_LATEST_VERSION" == "$_SHRENDD_CURRENT_VERSION" ]; then
           _SHRENDD_IS_UPTODATE="true"
@@ -485,49 +467,53 @@ function isUpToDate {
 }
 
 function initTargets {
-  export _SHRENDD_CONFIG_KEYS=$(keysFor "$_SHRENDD")
-  export _SHRENDD_DEFAULT_KEYS=$(keysFor "$_SHRENDD_DEFAULTS")
-  #echo "config keys: $_SHRENDD_CONFIG_KEYS"
-  #echo "default keys: $_SHRENDD_DEFAULT_KEYS"
-  #getTargetsD "$_SHRENDD_CONFIG_KEYS"
-  _target_keys=$(getTargets "$_SHRENDD_CONFIG_KEYS")
-  #echo "trying to load array of targets: $_target_keys"
-  if [ -z "$(echo $_target_keys | sed -e "s/ //g")" ]; then
-    shrenddEchoIfNotSilent "no targets... using default list"
-    #getTargetsD "$_SHRENDD_DEFAULT_KEYS"
-    _target_keys=$(getTargets "$_SHRENDD_DEFAULT_KEYS")
-  fi
+  if [[ -z "$GIVEN_TARGETS" ]]; then
+    export _SHRENDD_CONFIG_KEYS=$(keysFor "$_SHRENDD")
+    export _SHRENDD_DEFAULT_KEYS=$(keysFor "$_SHRENDD_DEFAULTS")
+    #echo "config keys: $_SHRENDD_CONFIG_KEYS"
+    #echo "default keys: $_SHRENDD_DEFAULT_KEYS"
+    #getTargetsD "$_SHRENDD_CONFIG_KEYS"
+    _target_keys=$(getTargets "$_SHRENDD_CONFIG_KEYS")
+    #echo "trying to load array of targets: $_target_keys"
+    if [ -z "$(echo $_target_keys | sed -e "s/ //g")" ]; then
+      shrenddEchoIfNotSilent "no targets... using default list"
+      #getTargetsD "$_SHRENDD_DEFAULT_KEYS"
+      _target_keys=$(getTargets "$_SHRENDD_DEFAULT_KEYS")
+    fi
 
-  _targets=""
-  for index in $_target_keys; do
-    index=$(echo "$index" | sed -e "s/$_SPACE_PLACE_HOLDER/ /g")
-    _target=$(shrenddOrDefault "$index" 0)
-    shrenddEchoIfNotSilent "checking: $_target"
-    if [ -z "$_targets" ] || [ "$_targets" == "" ]; then
-      :
-    else
-      _targets="$_targets "
-    fi
-    _targets="$_targets$_target"
-    if [[ $# -gt 0 && "${_target}" != "render" ]]; then
-      _target_source=$(shrenddOrDefault "shrendd.${_target}.source" 1)
-      if [[ "${_target_source}" == "null" ]]; then
-        _target_source=$(shrenddOrDefault "shrendd.default.source" 1)
+    _targets=""
+    for index in $_target_keys; do
+      index=$(echo "$index" | sed -e "s/$_SPACE_PLACE_HOLDER/ /g")
+      _target=$(shrenddOrDefault "$index" 0)
+      shrenddEchoIfNotSilent "checking: $_target"
+      if [ -z "$_targets" ] || [ "$_targets" == "" ]; then
+        :
+      else
+        _targets="$_targets "
       fi
-      _target_shrendd=$(shrenddOrDefault "shrendd.provided.${_target}" 1)
-      #cloneShrendd "$_GETTER" "$_target"
-      if [[ "$_target_shrendd" != "null" ]]; then
-        if [[ "$FORCE_SHRENDD_UPDATES" == "true" ]]; then
-          shrenddLog "initTargets: rm ${SHRENDD_DIR}/${_target}"
-          rm -rf $SHRENDD_DIR/$_target
+      _targets="$_targets$_target"
+      if [[ $# -gt 0 && "${_target}" != "render" ]]; then
+        _target_source=$(shrenddOrDefault "shrendd.${_target}.source" 1)
+        if [[ "${_target_source}" == "null" ]]; then
+          _target_source=$(shrenddOrDefault "shrendd.default.source" 1)
         fi
-        shrenddEchoIfNotSilent "shrendd.${_target}.source: ${_target_source}"
-        eval "${_target_source}"
+        _target_shrendd=$(shrenddOrDefault "shrendd.provided.${_target}" 1)
+        #cloneShrendd "$_GETTER" "$_target"
+        if [[ "$_target_shrendd" != "null" ]]; then
+          if [[ "$FORCE_SHRENDD_UPDATES" == "true" ]]; then
+            shrenddLog "initTargets: rm ${SHRENDD_DIR}/${_target}"
+            rm -rf "$SHRENDD_DIR/$_target"
+          fi
+          shrenddEchoIfNotSilent "shrendd.${_target}.source: ${_target_source}"
+          eval "${_target_source}"
+        fi
       fi
-    fi
-  done
-  shrenddEchoIfNotSilent "targets initialized"
-  export targets="$_targets"
+    done
+    shrenddEchoIfNotSilent "targets initialized"
+    export targets="$_targets"
+  else
+    export targets="$GIVEN_TARGETS"
+  fi
 }
 
 function cloneShrendd {
@@ -551,18 +537,18 @@ function clonePlugin {
   if [ "$_IS_UPTODATE_NOW" == "true" ]; then
     :
   else
-    if [ -d $SHRENDD_DIR ]; then
+    if [ -d "$SHRENDD_DIR" ]; then
       :
     else
       mkdir "$SHRENDD_DIR"
     fi
     shrenddEchoIfNotSilent "downloading $5:$3"
-    if [ -d $SHRENDD_DIR/$2 ]; then
+    if [ -d "$SHRENDD_DIR/$2" ]; then
       shrenddLog "clonePlugin: rm ${SHRENDD_DIR}/${2}"
-      rm -rf $SHRENDD_DIR/$2
+      rm -rf "$SHRENDD_DIR/$2"
     fi
     shrenddLog "clonePlugin: before downloading: rm ${SHRENDD_DIR}/${2}.zip"
-    rm -f $SHRENDD_DIR/$2.zip
+    rm -f "$SHRENDD_DIR/$2.zip"
     shrenddEchoIfNotSilent "downloading with $1...$2"
     #curlD or wgetD...
     if [[ "$_clone_parameters" == "null" ]]; then
@@ -575,9 +561,9 @@ function clonePlugin {
       shrenddEchoIfNotSilent "cloned locally, nothing to unzip."
     else
       shrenddEchoIfNotSilent "unzipping cloned file: $2.zip"
-      unzip -ao $SHRENDD_DIR/$2.zip -d $SHRENDD_DIR
+      unzip -ao "$SHRENDD_DIR/$2.zip" -d "$SHRENDD_DIR"
       shrenddLog "clonePlugin: after unzipping: rm ${SHRENDD_DIR}/${2}.zip"
-      rm $SHRENDD_DIR/$2.zip
+      rm "$SHRENDD_DIR/$2.zip"
     fi
   fi
 }
@@ -600,7 +586,7 @@ function initPlugins {
       else
         if [[ "$FORCE_SHRENDD_UPDATES" == "true" ]]; then
           shrenddLog "initPlugins: force updates: rm ${SHRENDD_DIR}/${_plug}"
-          rm -rf $SHRENDD_DIR/$_plug
+          rm -rf "$SHRENDD_DIR/$_plug"
         fi
         _clone_parameters=$(shrenddOrDefault "shrendd.plugins.$_plug.parameters")
         shrenddEchoIfNotSilent "  $_plug parameters: $_clone_parameters"
@@ -659,8 +645,8 @@ export _SHREND_YML="./shrendd.yml"
 if [[ -n "${SHREND_YML+x}" ]]; then
   export _SHREND_YML="$SHREND_YML"
 fi
-if [ -f $_SHREND_YML ]; then
-  export _SHRENDD=$(cat $_SHREND_YML)
+if [ -f "$_SHREND_YML" ]; then
+  export _SHRENDD=$(cat "$_SHREND_YML")
   shrenddEchoIfNotSilent "found shrendd.yml, will use values defined there, if no value specified, will use default values."
 else
   shrenddEchoIfNotSilent "no shrendd.yml found, using defaults. For more information on configuring shrendd, please see:"
@@ -685,7 +671,7 @@ fi
 ##check for yq, error if not present with message
 checkCommand "yq" 1
 
-if [ -d $(shrenddOrDefault "shrendd.test.local") ]; then
+if [ -d "$(shrenddOrDefault "shrendd.test.local")" ]; then
   export _GETTER="devD"
 else
   if [[ -z $(checkCommand "curl" 0) ]]; then
@@ -711,7 +697,7 @@ else
   echo "there is no shrendd, did you run in offline mode with no shrendd downloaded?"
   exit 42
 fi
-source $SHRENDD_DIR/parse_parameters.sh
+source "$SHRENDD_DIR/parse_parameters.sh"
 if [[ "$_getting" == "0" ]]; then
   shrenddStub
 fi
@@ -736,9 +722,9 @@ if [[ "$_getting" == "0" ]]; then
 fi
 
 #loop over targets
-if [[ "$_getting" == "0" ]]; then
-  initTargets "true"
-fi
+# if [[ "$_getting" == "0" ]]; then
+initTargets "true"
+# fi
 if [[ -n "${_JUST_INITIALIZE+x}" ]]; then
   :
 else
@@ -752,16 +738,16 @@ if [ "$_JUST_INITIALIZE" == "true" ]; then
   exit 0
 fi
 
-export _config_path=$(shrenddOrDefault shrendd.config.path)/${_config}
+export _config_path="$(shrenddOrDefault shrendd.config.path)/${_config}"
 shrenddEchoIfNotSilent "======================================================="
 shrenddEchoIfNotSilent "${_TEXT_INFO}                 best shrendds forever                 ${_CLEAR_TEXT_COLOR}"
 shrenddEchoIfNotSilent "using: $_config_path"
 if [[ $_stub == "false" ]]; then
-  source $SHRENDD_DIR/deploy.sh
+  source "$SHRENDD_DIR/deploy.sh"
   shrenddDeployRun
 else
   shrenddEchoIfNotSilent "stubbing: $_stub/toes"
-  source $SHRENDD_DIR/stub.sh
+  source "$SHRENDD_DIR/stub.sh"
 fi
 end_time=$SECONDS
 duration=$((end_time - start_time))
